### ISSUE TITLE
Question not issue

### ISSUE THREAD

**Issue by MilitaryNekoMaid** [renzuzu/vImageCreator#1]
I wonder why are you using screenshot-basic when this is more optimized? https://github.com/utkuali/utk_render
is there any issue with utk_render that i don't know or screenshot-basic is just easiest?

**Comment by renzuzu** [comment]
I totaly forgot utk render.. 

Yea this could be changed in dependency

If utk render support discord webhooks too.

I used screenshot basic because its a default fivemtool known by everyone

**Comment by Dokman** [comment]
the owners that they are "license:blabla" it can be another thing or how do they work?
