### ISSUE TITLE
No valid command

### ISSUE THREAD

**Issue by Kiba-Wolf** [renzuzu/vImageCreator#2]
![command](https://user-images.githubusercontent.com/76842680/140162114-0af5721e-3f54-44d4-8539-1a8e90f0ce8f.PNG)

**Comment by Kiba-Wolf** [comment]
Ok nevermind got it but now nothing happens after starting the screenshooting its just in the room and nothing happens

**Comment by Kiba-Wolf** [comment]
OK i dont know whats wrong now it works XD

**Comment by renzuzu** [comment]
Glad you fix it

Update it too. Removed limits of seconds to load custom addon cars.

You dont need update if you use this on local host
